name: Rust

permissions:
  contents: write

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v24
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Build
      run: nix build

    - name: Get short SHA
      id: short_sha
      run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Get version
      run: echo "version=$(./result/bin/radar --version | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT
      id: version

    - name: Compress artifact
      run: xz -c -k -e -9 ./result/bin/radar > radar-x86_64-musl.xz

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: radar-x86_64-musl.xz

    - name: Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        name: ${{ steps.version.outputs.version }}
        tag_name: v${{ steps.version.outputs.version }}-${{ steps.short_sha.outputs.short_sha }}
        files: radar-x86_64-musl.xz

    # - name: Release
    #   if: github.ref == 'refs/heads/master'
    #   uses: actions/create-release@v1
    #   id: create_release
    #   with:
    #     draft: false
    #     prerelease: false
    #     release_name: ${{ steps.version.outputs.version }}
    #     tag_name: v${{ steps.version.outputs.version }}-${{ steps.short_sha.outputs.short_sha }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #
    # - name: Upload Linux musl artifact
    #   if: github.ref == 'refs/heads/master'
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./radar.xz
    #     asset_name: radar-${{ steps.version.outputs.version }}-x86_64-musl.xz
    #     asset_content_type: application/octet-stream

    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
